[build]
  command = "npm run build"
  publish = ".next"
  environment = { NODE_VERSION = "16.20.2" }

[build.environment]
  NODE_VERSION = "16.20.2"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs" 