[build]
  command = "chmod +x ./netlify-build.sh && ./netlify-build.sh"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.18.0"
  NEXT_TELEMETRY_DISABLED = "1"
  
  # Prisma configuration
  PRISMA_SKIP_POSTINSTALL_GENERATE = "true"
  
  # Database
  DATABASE_URL = "${DATABASE_URL}"
  
  # Supabase
  NEXT_PUBLIC_SUPABASE_URL = "${NEXT_PUBLIC_SUPABASE_URL}"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "${NEXT_PUBLIC_SUPABASE_ANON_KEY}"
  NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY = "${NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY}"
  
  # JWT
  NEXT_PUBLIC_SUPABASE_JWT_SECRET = "${NEXT_PUBLIC_SUPABASE_JWT_SECRET}"
  NEXT_PUBLIC_SUPABASE_JWT_EXPIRES_IN = "${NEXT_PUBLIC_SUPABASE_JWT_EXPIRES_IN}"
  NEXT_PUBLIC_SUPABASE_JWT_REFRESH_TOKEN_EXPIRES_IN = "${NEXT_PUBLIC_SUPABASE_JWT_REFRESH_TOKEN_EXPIRES_IN}"
  NEXT_PUBLIC_SUPABASE_JWT_ALGORITHM = "${NEXT_PUBLIC_SUPABASE_JWT_ALGORITHM}"
  NEXT_PUBLIC_SUPABASE_JWT_SECRET_KEY = "${NEXT_PUBLIC_SUPABASE_JWT_SECRET_KEY}"
  NEXT_PUBLIC_SUPABASE_JWT_PRIVATE_KEY = "${NEXT_PUBLIC_SUPABASE_JWT_PRIVATE_KEY}"
  NEXT_PUBLIC_SUPABASE_JWT_PUBLIC_KEY = "${NEXT_PUBLIC_SUPABASE_JWT_PUBLIC_KEY}"
  
  # M-Pesa
  MPESA_SHORTCODE = "9955363"

# Add a build plugin for Next.js
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Disable Netlify's dependency caching for Prisma
[build]
  ignore = "git diff --quiet HEAD^ HEAD ."